# Generated by Django 2.2.4 on 2020-01-10 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('no_of_members', models.SmallIntegerField(default=0)),
                ('principal', models.IntegerField()),
                ('commission_percent', models.IntegerField(default=5)),
                ('balance', models.IntegerField(default=0)),
                ('shortage', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('period', models.SmallIntegerField()),
                ('dues', models.SmallIntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('next_auction', models.DateField(null=True)),
                ('is_multiple_auction', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
                ('end_date', models.TimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='globals.Member')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='chit_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, choices=[(-1, 'UNKNOWN'), (1, 'PAID'), (0, 'UN_PAID'), (2, 'CHIT_BENIFIT')], default=1, null=True)),
                ('bid_date', models.DateField()),
                ('chitbatch', models.ForeignKey(on_delete='CASCADE', related_name='payments', to='chits.ChitBatch')),
                ('member', models.ForeignKey(on_delete='CASCADE', related_name='payments', to='globals.Member')),
            ],
        ),
        migrations.CreateModel(
            name='BidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_date', models.DateField()),
                ('bid_amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('bid_count', models.SmallIntegerField(default=1)),
                ('shortage', models.IntegerField(default=0)),
                ('bidder', models.ForeignKey(on_delete='CASCADE', related_name='bids', to='globals.Member')),
                ('chitbatch', models.ForeignKey(on_delete='CASCADE', related_name='records', to='chits.ChitBatch')),
                ('payment_record', models.ManyToManyField(to='chits.PaymentRecord')),
            ],
            options={
                'get_latest_by': 'bid_date',
            },
        ),
    ]
